# Generated by Django 5.0.1 on 2024-01-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgstudentdetails',
            name='percentageoptained',
            field=models.CharField(max_length=5),
        ),
    ]
