# Generated by Django 5.0.1 on 2024-02-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_pgstudentdetails_percentageoptained'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='pg_bc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='pg_mbc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='pg_oc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='pg_sc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='pg_st',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pgstudentdetails',
            name='fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pgstudentdetails',
            name='resevation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
