# Generated by Django 5.0.1 on 2024-01-31 07:39

import django.db.models.deletion
import myapp.helperfunctions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_pgstudentdetails_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFileOFUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=myapp.helperfunctions.Photo_rename, validators=[myapp.helperfunctions.validate_image_size])),
                ('aadhar', models.ImageField(upload_to=myapp.helperfunctions.aadhar_rename, validators=[myapp.helperfunctions.validate_image_size])),
                ('marksheet', models.ImageField(upload_to=myapp.helperfunctions.Marksheet_rename, validators=[myapp.helperfunctions.validate_image_size])),
                ('community_doc', models.ImageField(upload_to=myapp.helperfunctions.community_rename, validators=[myapp.helperfunctions.validate_image_size])),
                ('special_doc', models.ImageField(blank=True, null=True, upload_to=myapp.helperfunctions.special_documents_rename, validators=[myapp.helperfunctions.validate_image_size])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.customuserstudent')),
            ],
        ),
    ]
