# Generated by Django 5.0.1 on 2024-02-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_department_pg_bc_department_pg_mbc_department_pg_oc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserstaff',
            name='role',
            field=models.CharField(choices=[('controler', 'CONTROLER'), ('department', 'DEPARTMENT'), ('principal', 'PRINCIPAL'), ('office', 'OFFICE')], max_length=10, null=True),
        ),
    ]
