# Generated by Django 5.0.1 on 2024-02-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customuserstaff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserstudent',
            name='role',
            field=models.CharField(default='student', max_length=10),
        ),
    ]
