# Generated by Django 5.0.1 on 2024-02-05 03:43

import myapp.helperfunctions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customuserstudent_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgstudentdetails',
            old_name='marksheet',
            new_name='marksheet_doc',
        ),
        migrations.RenameField(
            model_name='pgstudentdetails',
            old_name='photo',
            new_name='photo_doc',
        ),
        migrations.AddField(
            model_name='department',
            name='pg_bcm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='pg_sca',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pgstudentdetails',
            name='aadhar_doc',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.helperfunctions.aadhar_rename, validators=[myapp.helperfunctions.validate_image_size]),
        ),
        migrations.AddField(
            model_name='pgstudentdetails',
            name='acadamic_year',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentdetails',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentdetails',
            name='degree',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentdetails',
            name='fathername',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentdetails',
            name='instute_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentdetails',
            name='maratail_status',
            field=models.CharField(blank=True, choices=[('single', 'SINGLE'), ('married', 'MARRIED')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentdetails',
            name='medium',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentdetails',
            name='mode_of_study',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentdetails',
            name='pysically_chalanged',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentdetails',
            name='religion',
            field=models.CharField(blank=True, choices=[('hindu', 'HINDU'), ('muslim', 'MUSLIM'), ('cristin', 'CRISTIN')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentdetails',
            name='remark',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentdetails',
            name='sports',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pgstudentdetails',
            name='aadhar',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
