# Generated by Django 5.0.1 on 2024-02-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_marksheet_pgstudentdetails_marksheet_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgstudentdetails',
            name='status',
            field=models.CharField(choices=[('controler', 'CONTROLER'), ('department', 'DEPARTMENT'), ('admited', 'ADMITED'), ('rejected', 'REJECTED')], max_length=30),
        ),
    ]
