# Generated by Django 5.0.1 on 2024-02-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_pgstudentdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgstudentdetails',
            name='status',
            field=models.CharField(choices=[('applied', 'APPLIED'), ('controler', 'CONTROLER'), ('department', 'DEPARTMENT'), ('admited', 'ADMITED'), ('rejected', 'REJECTED')], max_length=30),
        ),
    ]
