# Generated by Django 5.0.1 on 2024-02-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_pgstudentdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgstudentdetails',
            name='acceptorrejectedBy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
