# Generated by Django 5.0.1 on 2024-02-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_userreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userreport',
        ),
    ]
