# Generated by Django 5.0.1 on 2024-02-11 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_userreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserstaff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
    ]
