# Generated by Django 5.0.1 on 2024-02-13 04:08

import myapp.helperfunctions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_customuserstaff_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgstudentdetails',
            name='tc_doc',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.helperfunctions.community_rename, validators=[myapp.helperfunctions.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='pgstudentdetails',
            name='maratail_status',
            field=models.CharField(blank=True, choices=[('single', 'SINGLE'), ('married', 'MARRIED')], default='single', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pgstudentdetails',
            name='pysically_chalanged',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pgstudentdetails',
            name='sports',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=5, null=True),
        ),
    ]
