# Generated by Django 5.0.1 on 2024-02-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_pgstudentdetails_tc_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgstudentdetails',
            name='aproved',
            field=models.BooleanField(default=False),
        ),
    ]
